### PR TITLE
Fix some typo, solved issue #83

### LINKED ISSUE #83: Version 0.0.23 fails
Firstly thanks for this awesome project and all the contributors' brilliant works, this component save loads of my times!

The error occured while upgrading to version 0.0.23 as follow:

screen shot 2016-03-16 at 21 52 05

This is related to PR #71 due to some type, will have a PR for this in a minute.

### PR DESCRIPTION
**Pull request by ianlin**
Follow up #71

### CODE REVIEW

**Comment by ianlin** [comment]
1. `this.props.style` should be `this.props.styles`
2. should check if the property `textInputContainer` exists in `this.props.styles` and `nextProps.styles`

**Comment by FaridSafi** [comment]
much thanks @ianlin

**Comment by FaridSafi** [comment]
new npm version published

**Comment by ianlin** [comment]
Thanks! :)

**Pull request merged**
