### PR TITLE
scrollWithoutAnimationTo(vertical, horizontal)

### PR DESCRIPTION
**Pull request by Alchemist85K**
scrollWithoutAnimationTo(vertical, horizontal)

### CODE REVIEW

**Comment by FaridSafi** [comment]
Thank you, do you know if it's related to some react-native core breaking change?

**Comment by FaridSafi** [comment]
It seems that will be different in 0.20
https://github.com/facebook/react-native/commit/6941c4e027abb582d7cef0e7c3b9b7ebf51bc070

**Comment by FaridSafi** [comment]
before I publish a new version, do you confirm https://github.com/FaridSafi/react-native-gifted-messenger/blob/master/GiftedMessenger.js#L257 doesn't need to be changed as well ?

**Comment by Alchemist85K** [comment]
No, I didn't check it.
But I think it would be okay because the first parameter of `scrollTo()` function is y value.
And Would it be better to replace `scrollWithoutAnimationTo()` with `scrollTo({x, y, animated: false})`?

**Comment by FaridSafi** [comment]
I guess ```js scrollTo({x, y, animated: false}) ``` is not working yet with 0.19

**Comment by Alchemist85K** [comment]
Oh, I got it. Your project helps me a lot. Thank you.

**Pull request merged**
